# Vectorized alpha layer demo

Runs `src2/alpha_engine.py` against a synthetic price panel (no network
call needed) and shows the pipeline as plain, inspectable DataFrames:
`price -> metrics -> filter/rank -> target_weight`.

Also sanity-checks the vectorized mean-reversion score against the
existing per-ticker `src/scorers/mean_reversion_scorers.MeanReversionScorer`
class, to confirm the two agree before trusting the vectorized version.

In [1]:
import sys
sys.path.insert(0, '..')

import numpy as np
import pandas as pd

from src2 import vectorized_scorers, alpha_engine
from src.scorers.mean_reversion_scorers import MeanReversionScorer

## 1. Synthetic price panel (date x ticker)

In [2]:
tickers='ALGN,AAPL,PANW,AMD,ZS,MDLZ,XEL,VRSN,INSM,ON,WDAY,ENPH,DLTR,ADI,COST,ABNB,CEG,MSFT,GOOGL,CDNS,PYPL,FAST,JD,MTCH,SNPS,LULU,CMCSA,ADBE,ADSK'.split(',')

In [3]:
from src import data_broker
broker = data_broker.DataBroker(tickers=tickers, start_date="2022-01-01", end_date="2026-04-01")
universe_data = broker.fetch_universe_data()

[                       0%                       ]

[*******               14%                       ]  4 of 29 completed

[*************         28%                       ]  8 of 29 completed

[*************         28%                       ]  8 of 29 completed

[******************    38%                       ]  11 of 29 completed

[********************  41%                       ]  12 of 29 completed

[**********************45%                       ]  13 of 29 completed

[**********************48%                       ]  14 of 29 completed

[**********************52%                       ]  15 of 29 completed

[**********************55%*                      ]  16 of 29 completed

[**********************59%***                    ]  17 of 29 completed

[**********************62%*****                  ]  18 of 29 completed

[**********************66%*******                ]  19 of 29 completed

[**********************69%********               ]  20 of 29 completed

[**********************69%********               ]  20 of 29 completed

[**********************83%***************        ]  24 of 29 completed

[**********************86%****************       ]  25 of 29 completed

[**********************90%******************     ]  26 of 29 completed

[**********************93%********************   ]  27 of 29 completed

[**********************97%********************** ]  28 of 29 completed

[*********************100%***********************]  29 of 29 completed

In [4]:
price_df=universe_data['price']

In [5]:
# rng = np.random.default_rng(0)
# dates = pd.bdate_range("2022-01-01", "2023-12-31")
# tickers = [f"T{i}" for i in range(8)]

# log_returns = rng.normal(loc=0.0002, scale=0.015, size=(len(dates), len(tickers)))
# price_df = pd.DataFrame(100 * np.exp(np.cumsum(log_returns, axis=0)), index=dates, columns=tickers)
# price_df.head()

## 2. Rebalance dates (month-end, matches CalendarIterator's default)

In [6]:
world_data_dict=universe_data

In [7]:
from src import calendar_iterator
calendar = calendar_iterator.CalendarIterator(world_data_dict, interval="ME")
rebalance_dates = calendar.generate_rebalance_dates()

In [8]:
rebalance_dates[:3]

[Timestamp('2022-01-31 00:00:00'),
 Timestamp('2022-02-28 00:00:00'),
 Timestamp('2022-03-31 00:00:00')]

In [9]:
# rebalance_dates = pd.Series(dates, index=dates).resample("ME").last().dropna().tolist()
# len(rebalance_dates), rebalance_dates[:3]

## 3. Metrics table -- one row per (date, ticker), fully inspectable

In [10]:
WINDOW = 60

df_metrics, df_ranked = alpha_engine.build_target_weight_table(
    price_df,
    rebalance_dates,
    score_fn=vectorized_scorers.rolling_mean_reversion_score,
    window=WINDOW,
    top_percent=0.25,
    allocation_type="equal",
)
df_metrics.head(10)

        date ticker     score   z_score  raw_z_score  window_mean  window_std
0 2022-01-31   ALGN  0.466693 -0.466693    -0.466693   520.869496   55.517293
1 2022-01-31   AAPL -0.727532  0.727532     0.727532   166.062896    6.609381
2 2022-01-31   PANW -0.398864  0.398864     0.398864    84.915417    3.304162
3 2022-01-31    AMD  0.943130 -0.943130    -0.943130   126.839999   13.349167
4 2022-01-31     ZS -0.049596  0.049596     0.049596   256.129498   19.769545
5 2022-01-31   MDLZ  0.413253 -0.413253    -0.413253    59.587006    0.512306
6 2022-01-31    XEL -1.515563  1.515563     1.515563    59.304027    0.596821
7 2022-01-31   VRSN  0.703379 -0.703379    -0.703379   223.682178   13.858302
8 2022-01-31   INSM  0.452879 -0.452879    -0.452879    23.700000    2.252257
9 2022-01-31     ON  0.431625 -0.431625    -0.431625    61.594499    6.011007

## 4. Filtered/ranked/target-weight table

In [11]:
df_ranked.head(16)

,date,ticker,score,z_score,raw_z_score,window_mean,window_std,filtered_out,rank,target_weight
0,2022-01-31,ALGN,0.466693,-0.466693,-0.466693,520.869496,55.517293,False,7.0,0.142857
1,2022-01-31,AAPL,-0.727532,0.727532,0.727532,166.062896,6.609381,False,25.0,0.000000
2,2022-01-31,PANW,-0.398864,0.398864,0.398864,84.915417,3.304162,False,23.0,0.000000
3,2022-01-31,AMD,0.943130,-0.943130,-0.943130,126.839999,13.349167,False,1.0,0.142857
4,2022-01-31,ZS,-0.049596,0.049596,0.049596,256.129498,19.769545,False,21.0,0.000000
5,2022-01-31,MDLZ,0.413253,-0.413253,-0.413253,59.587006,0.512306,False,11.0,0.000000
6,2022-01-31,XEL,-1.515563,1.515563,1.515563,59.304027,0.596821,False,28.0,0.000000
7,2022-01-31,VRSN,0.703379,-0.703379,-0.703379,223.682178,13.858302,False,4.0,0.142857
8,2022-01-31,INSM,0.452879,-0.452879,-0.452879,23.700000,2.252257,False,9.0,0.000000
9,2022-01-31,ON,0.431625,-0.431625,-0.431625,61.594499,6.011007,False,10.0,0.000000
10,2022-01-31,WDAY,-0.543481,0.543481,0.543481,247.727499,9.719745,False,24.0,0.000000
11,2022-01-31,ENPH,0.075788,-0.075788,-0.075788,141.790501,17.423693,False,20.0,0.000000
12,2022-01-31,DLTR,0.466772,-0.466772,-0.466772,133.711001,5.336648,False,6.0,0.142857
13,2022-01-31,ADI,0.349145,-0.349145,-0.349145,154.176395,6.606770,False,15.0,0.000000
14,2022-01-31,COST,0.210396,-0.210396,-0.210396,486.089607,27.828293,False,17.0,0.000000
15,2022-01-31,ABNB,0.363560,-0.363560,-0.363560,157.706500,10.277531,False,12.0,0.000000

## 5. Cross-check: vectorized score vs the existing per-ticker `MeanReversionScorer`

Picks one (date, ticker) pair, replays the same window slice through the
class-based scorer, and confirms the two numbers agree within tolerance.

In [12]:
check_date = rebalance_dates[10]
check_ticker = tickers[3]

vectorized_score = df_metrics.loc[
    (df_metrics["date"] == check_date) & (df_metrics["ticker"] == check_ticker), "score"
].iloc[0]

history = price_df.loc[:check_date, check_ticker].dropna()
window_slice = history.iloc[-WINDOW:] if len(history) >= WINDOW else history
classic_score, classic_metrics = MeanReversionScorer(min_periods=20, clip_z=3.0).compute_score(window_slice.values)

print(f"vectorized: {vectorized_score:.6f}")
print(f"classic:    {classic_score:.6f}")
print(f"match: {abs(vectorized_score - classic_score) < 1e-6}")

vectorized: -1.221381
classic:    -1.221381
match: True

In [13]:
vectorized_score

np.float64(-1.2213814046017721)

## 6. Liquidity filter (vectorized equivalent of src/filters/liquidfilter.py)

In [14]:
volume_df = universe_data["volume"]

liquidity_filter = alpha_engine.make_liquidity_filter(
    price_df, volume_df, min_dollar_volume=50_000_000.0, volume_window=20,
)

df_metrics_liq, df_ranked_liq = alpha_engine.build_target_weight_table(
    price_df,
    rebalance_dates,
    score_fn=vectorized_scorers.rolling_mean_reversion_score,
    window=WINDOW,
    top_percent=0.25,
    allocation_type="equal",
    filter_fn=liquidity_filter,
)

print(f"filtered out (null_filter):     {df_ranked['filtered_out'].sum()} / {len(df_ranked)}")
print(f"filtered out (liquidity_filter): {df_ranked_liq['filtered_out'].sum()} / {len(df_ranked_liq)}")
df_ranked_liq[df_ranked_liq['filtered_out']].head(10)

filtered out (null_filter):     0 / 1479
filtered out (liquidity_filter): 27 / 1479

,date,ticker,score,z_score,raw_z_score,window_mean,window_std,filtered_out,rank,target_weight
8,2022-01-31,INSM,0.452879,-0.452879,-0.452879,23.700000,2.252257,True,NaN,0.0
16,2022-01-31,CEG,-2.584733,2.584733,2.584733,41.573275,1.819706,True,NaN,0.0
37,2022-02-28,INSM,-0.301109,0.301109,0.301109,23.386410,1.705658,True,NaN,0.0
66,2022-03-31,INSM,-0.368318,0.368318,0.368318,23.074667,1.154799,True,NaN,0.0
95,2022-04-29,INSM,1.352562,-1.352562,-1.352562,23.366500,1.032485,True,NaN,0.0
124,2022-05-31,INSM,1.503915,-1.503915,-1.503915,22.206500,2.251789,True,NaN,0.0
153,2022-06-30,INSM,0.436898,-0.436898,-0.436898,20.830000,2.540640,True,NaN,0.0
182,2022-07-29,INSM,-0.796406,0.796406,0.796406,20.472667,2.068460,True,NaN,0.0
211,2022-08-31,INSM,-0.601202,0.601202,0.601202,22.821167,2.992062,True,NaN,0.0
240,2022-09-30,INSM,1.337504,-1.337504,-1.337504,24.116667,1.926473,True,NaN,0.0

## 7. Full backtest using the precomputed target_weight table

In [15]:
from src2 import run_vectorized

g_state, audit_ledger = run_vectorized.run_vectorized(
    df_ranked,
    world_data_dict,
    rebalance_dates,
    initial_capital=100_000.0,
)

df_nav = g_state.export_nav_dataframe()
df_nav.tail()

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY AMD ... 122.09@116.78, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY DLTR ... 106.21@134.24, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY ALGN ... 28.03@508.56, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY CDNS ... 94.04@151.61, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY VRSN ... 66.74@213.61, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY FAST ... 560.16@25.45, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-02-01 00:00:00:CORE_BUY MTCH ... 132.47@107.62, fee: 14.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL AMD ... 122.09@113.83, fee: 13.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL DLTR ... 106.21@139.71, fee: 14.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL ALGN ... 28.03@500.97, fee: 14.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL CDNS ... 94.04@150.53, fee: 14.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL VRSN ... 66.74@212.81, fee: 14.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_SELL MTCH ... 132.47@106.02, fee: 14.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY ZS ... 56.49@247.83, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY ADSK ... 65.42@214.0, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY MDLZ ... 245.64@56.99, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY CMCSA ... 375.46@37.29, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY FAST ... 44.37@23.22, fee: 1.03

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY PYPL ... 132.58@105.6, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-03-01 00:00:00:CORE_BUY ADBE ... 30.0@466.68, fee: 14.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_SELL ZS ... 56.49@246.21, fee: 13.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_SELL FAST ... 604.53@26.88, fee: 16.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_SELL PYPL ... 132.58@115.67, fee: 15.34

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY AMD ... 133.69@108.19, fee: 14.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY ADSK ... 2.67@213.04, fee: 0.57

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY JD ... 279.38@51.77, fee: 14.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY ALGN ... 32.4@446.41, fee: 14.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY MDLZ ... 10.69@56.59, fee: 0.61

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY CMCSA ... 2.93@38.34, fee: 0.11

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-04-01 00:00:00:CORE_BUY ADBE ... 1.66@458.19, fee: 0.76

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_SELL ADSK ... 68.09@192.9, fee: 13.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_SELL JD ... 279.38@55.52, fee: 15.51

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_SELL MDLZ ... 256.33@56.82, fee: 14.57

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_SELL ADBE ... 31.66@407.29, fee: 12.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY AMD ... 10.25@89.84, fee: 0.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY GOOGL ... 111.59@115.56, fee: 12.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY ALGN ... 9.45@308.88, fee: 2.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY CMCSA ... 17.16@32.7, fee: 0.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY VRSN ... 74.81@172.38, fee: 12.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY MTCH ... 166.45@77.47, fee: 12.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-05-02 00:00:00:CORE_BUY WDAY ... 61.88@208.41, fee: 12.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_SELL AMD ... 143.94@101.22, fee: 14.57

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_SELL GOOGL ... 111.59@112.89, fee: 12.6

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_SELL CMCSA ... 395.55@35.51, fee: 14.05

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_SELL VRSN ... 1.98@171.76, fee: 0.34

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_SELL MTCH ... 166.45@76.08, fee: 12.66

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY ZS ... 83.74@148.94, fee: 12.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY COST ... 28.62@435.83, fee: 12.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY INSM ... 695.6@17.93, fee: 12.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY ALGN ... 5.31@265.17, fee: 1.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY ABNB ... 106.85@116.72, fee: 12.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-06-01 00:00:00:CORE_BUY WDAY ... 17.97@156.56, fee: 2.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL ZS ... 83.74@155.37, fee: 13.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL COST ... 28.62@463.27, fee: 13.26

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL INSM ... 695.6@20.89, fee: 14.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL ALGN ... 47.16@247.34, fee: 11.66

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL VRSN ... 72.83@168.26, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_SELL WDAY ... 79.85@142.35, fee: 11.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY ADI ... 91.56@133.63, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY AMD ... 166.08@73.67, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY ON ... 261.22@46.84, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY ADSK ... 70.38@173.86, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY ABNB ... 27.32@91.41, fee: 2.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY PYPL ... 172.85@70.79, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-07-01 00:00:00:CORE_BUY ADBE ... 33.21@368.48, fee: 12.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL ADI ... 91.56@160.32, fee: 14.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL AMD ... 166.08@96.78, fee: 16.07

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL ON ... 261.22@63.66, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL ADSK ... 70.38@218.14, fee: 15.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL PYPL ... 172.85@87.8, fee: 15.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_SELL ADBE ... 33.21@411.09, fee: 13.65

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY ZS ... 98.87@153.5, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY JD ... 287.53@52.78, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY CMCSA ... 497.21@30.52, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY ABNB ... 2.71@111.2, fee: 0.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY MTCH ... 214.97@70.6, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY PANW ... 179.37@84.61, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-08-01 00:00:00:CORE_BUY WDAY ... 97.55@155.58, fee: 15.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_SELL ZS ... 98.87@145.57, fee: 14.39

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_SELL JD ... 287.53@56.69, fee: 16.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_SELL ABNB ... 136.88@113.4, fee: 15.52

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_SELL PANW ... 179.37@90.86, fee: 16.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_SELL WDAY ... 97.55@161.09, fee: 15.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY ADI ... 105.32@141.58, fee: 14.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY DLTR ... 108.54@137.38, fee: 14.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY GOOGL ... 137.09@108.78, fee: 14.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY ALGN ... 60.68@245.74, fee: 14.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY CMCSA ... 0.87@30.03, fee: 0.03

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY MTCH ... 65.75@53.24, fee: 3.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-09-01 00:00:00:CORE_BUY ADBE ... 40.24@370.53, fee: 14.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_SELL ADI ... 105.32@136.36, fee: 14.36

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_SELL DLTR ... 108.54@141.65, fee: 15.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_SELL GOOGL ... 0.11@97.77, fee: 0.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_SELL MTCH ... 280.73@48.28, fee: 13.55

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_SELL ADBE ... 40.24@285.24, fee: 11.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY AAPL ... 95.48@139.84, fee: 13.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY JD ... 300.18@44.48, fee: 13.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY ALGN ... 1.42@215.64, fee: 0.31

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY MDLZ ... 262.76@50.82, fee: 13.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY CMCSA ... 39.11@24.93, fee: 0.98

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-10-03 00:00:00:CORE_BUY XEL ... 230.9@57.83, fee: 13.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_SELL AAPL ... 95.48@147.89, fee: 14.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_SELL MDLZ ... 262.76@55.79, fee: 14.66

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_SELL CMCSA ... 537.2@25.91, fee: 13.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_SELL XEL ... 230.9@58.15, fee: 13.43

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY ON ... 209.51@61.74, fee: 12.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY INSM ... 739.17@17.5, fee: 12.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY GOOGL ... 7.68@89.67, fee: 0.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY JD ... 75.34@34.53, fee: 2.6

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY ALGN ... 5.09@193.06, fee: 0.98

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY ABNB ... 118.62@109.05, fee: 12.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-11-01 00:00:00:CORE_BUY PYPL ... 156.99@82.4, fee: 12.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_SELL ON ... 209.51@73.99, fee: 15.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_SELL GOOGL ... 144.66@100.1, fee: 14.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_SELL JD ... 375.52@50.17, fee: 18.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY ZS ... 99.36@144.5, fee: 14.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY ADSK ... 69.38@206.93, fee: 14.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY INSM ... 13.95@19.12, fee: 0.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY AAPL ... 98.45@145.83, fee: 14.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY ALGN ... 4.17@201.77, fee: 0.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY ABNB ... 23.51@101.27, fee: 2.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2022-12-01 00:00:00:CORE_BUY PYPL ... 27.89@77.86, fee: 2.17

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_SELL INSM ... 753.11@19.18, fee: 14.44

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_SELL ALGN ... 71.36@212.28, fee: 15.15

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_SELL PYPL ... 184.88@73.94, fee: 13.67

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY ZS ... 18.93@110.19, fee: 2.09

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY ADSK ... 1.04@185.15, fee: 0.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY COST ... 29.97@433.82, fee: 13.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY GOOGL ... 147.17@88.34, fee: 13.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY AAPL ... 7.56@122.98, fee: 0.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY ABNB ... 11.43@84.9, fee: 0.97

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-01-03 00:00:00:CORE_BUY PANW ... 187.81@69.22, fee: 13.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL ZS ... 0.52@131.52, fee: 0.07

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL ADSK ... 70.43@222.19, fee: 15.65

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL COST ... 29.97@495.68, fee: 14.85

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL AAPL ... 106.01@143.0, fee: 15.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL GOOGL ... 147.17@99.55, fee: 14.65

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL ABNB ... 153.56@113.99, fee: 17.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_SELL PANW ... 187.81@79.86, fee: 15.0

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY CEG ... 185.83@83.09, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY DLTR ... 100.57@153.54, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY MDLZ ... 255.12@60.53, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY LULU ... 48.91@315.71, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY ENPH ... 67.98@227.14, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-02-01 00:00:00:CORE_BUY XEL ... 249.69@61.84, fee: 15.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_SELL ZS ... 117.76@128.44, fee: 15.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_SELL DLTR ... 100.57@148.12, fee: 14.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_SELL MDLZ ... 4.59@58.22, fee: 0.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_SELL LULU ... 48.91@309.49, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_SELL ENPH ... 67.98@212.95, fee: 14.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY CEG ... 15.06@72.59, fee: 1.09

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY JD ... 354.03@41.08, fee: 14.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY VRSN ... 75.22@193.34, fee: 14.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY MTCH ... 363.93@39.96, fee: 14.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY ADBE ... 44.97@323.38, fee: 14.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-03-01 00:00:00:CORE_BUY XEL ... 9.78@56.21, fee: 0.55

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_SELL MDLZ ... 250.53@64.04, fee: 16.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_SELL VRSN ... 75.22@210.15, fee: 15.81

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_SELL ADBE ... 44.97@380.08, fee: 17.09

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_SELL XEL ... 259.48@60.47, fee: 15.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY CEG ... 2.75@74.81, fee: 0.21

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY DLTR ... 102.62@148.01, fee: 15.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY INSM ... 874.44@17.37, fee: 15.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY JD ... 45.83@38.09, fee: 1.75

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY ENPH ... 74.97@202.6, fee: 15.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY MTCH ... 48.59@36.92, fee: 1.8

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-04-03 00:00:00:CORE_BUY PYPL ... 203.49@74.64, fee: 15.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_SELL CEG ... 203.64@75.23, fee: 15.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_SELL DLTR ... 102.62@153.67, fee: 15.77

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_SELL INSM ... 874.44@20.17, fee: 17.64

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_SELL MTCH ... 412.52@34.54, fee: 14.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_SELL PYPL ... 203.49@74.47, fee: 15.15

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY ADI ... 84.9@173.07, fee: 14.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY ON ... 187.6@78.33, fee: 14.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY ZS ... 165.59@88.74, fee: 14.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY ADSK ... 74.79@196.47, fee: 14.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY JD ... 55.44@32.36, fee: 1.8

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY ENPH ... 16.76@160.59, fee: 2.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-05-01 00:00:00:CORE_BUY WDAY ... 78.86@186.34, fee: 14.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_SELL ON ... 187.6@87.95, fee: 16.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_SELL ZS ... 165.59@135.09, fee: 22.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_SELL ADSK ... 74.79@203.3, fee: 15.21

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_SELL ENPH ... 91.73@181.47, fee: 16.65

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_SELL WDAY ... 78.86@215.31, fee: 16.98

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY ADI ... 12.47@171.05, fee: 2.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY DLTR ... 128.22@129.56, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY JD ... 73.7@31.48, fee: 2.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY ALGN ... 55.9@297.2, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY ABNB ... 148.11@112.16, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY PYPL ... 265.76@62.51, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-06-01 00:00:00:CORE_BUY XEL ... 291.9@56.91, fee: 16.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_SELL ADI ... 97.37@185.13, fee: 18.03

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_SELL DLTR ... 4.83@147.47, fee: 0.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_SELL ALGN ... 55.9@344.59, fee: 19.26

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_SELL ABNB ... 148.11@132.35, fee: 19.6

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY GOOGL ... 152.66@118.85, fee: 18.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY JD ... 38.68@32.05, fee: 1.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY MDLZ ... 269.2@67.4, fee: 18.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY ENPH ... 107.01@169.55, fee: 18.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY PYPL ... 3.76@67.52, fee: 0.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-07-03 00:00:00:CORE_BUY XEL ... 28.01@56.87, fee: 1.59

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_SELL DLTR ... 123.39@153.03, fee: 18.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_SELL GOOGL ... 152.66@130.39, fee: 19.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_SELL JD ... 567.68@36.51, fee: 20.72

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_SELL PYPL ... 269.52@74.88, fee: 20.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY AMD ... 160.29@117.6, fee: 18.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY MDLZ ... 8.13@68.17, fee: 0.55

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY LULU ... 49.45@381.21, fee: 18.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY MSFT ... 57.37@328.57, fee: 18.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY VRSN ... 90.52@208.24, fee: 18.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY ENPH ... 18.71@150.32, fee: 2.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-08-01 00:00:00:CORE_BUY XEL ... 13.2@56.75, fee: 0.75

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_SELL LULU ... 49.45@404.19, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_SELL MSFT ... 57.37@321.74, fee: 18.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_SELL VRSN ... 90.52@202.08, fee: 18.29

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY ADI ... 102.17@174.62, fee: 17.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY AMD ... 3.2@109.45, fee: 0.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY DLTR ... 150.25@118.74, fee: 17.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY JD ... 573.81@31.09, fee: 17.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY MDLZ ... 2.72@63.89, fee: 0.17

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY ENPH ... 13.25@128.73, fee: 1.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-09-01 00:00:00:CORE_BUY XEL ... 17.53@51.03, fee: 0.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_SELL ADI ... 102.17@167.92, fee: 17.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_SELL AMD ... 163.48@103.27, fee: 16.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_SELL MDLZ ... 280.06@63.18, fee: 17.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_SELL ENPH ... 138.97@116.84, fee: 16.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_SELL XEL ... 350.63@50.14, fee: 17.58

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY DLTR ... 8.8@104.66, fee: 0.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY AAPL ... 96.74@171.58, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY JD ... 54.15@26.51, fee: 1.44

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY ALGN ... 55.37@299.76, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY FAST ... 646.74@25.67, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY MTCH ... 453.63@36.59, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-10-02 00:00:00:CORE_BUY WDAY ... 77.69@213.66, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL DLTR ... 159.05@111.49, fee: 17.73

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL AAPL ... 96.74@171.8, fee: 16.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL JD ... 627.96@23.1, fee: 14.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL FAST ... 646.74@27.73, fee: 17.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL MTCH ... 453.63@28.12, fee: 12.76

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_SELL WDAY ... 77.69@211.46, fee: 16.43

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY ADI ... 99.24@152.42, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY ON ... 233.29@64.84, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY GOOGL ... 120.69@125.34, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY ALGN ... 27.36@183.21, fee: 5.02

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY CMCSA ... 428.0@35.34, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY ENPH ... 197.14@76.73, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-11-01 00:00:00:CORE_BUY PYPL ... 295.35@51.22, fee: 15.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_SELL ADI ... 99.24@176.06, fee: 17.47

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_SELL ALGN ... 3.27@220.45, fee: 0.72

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_SELL ENPH ... 32.73@106.52, fee: 3.49

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_SELL PYPL ... 295.35@59.14, fee: 17.47

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_BUY ON ... 2.84@74.18, fee: 0.21

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_BUY GOOGL ... 13.3@130.7, fee: 1.74

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_BUY JD ... 705.31@24.76, fee: 17.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_BUY CMCSA ... 62.87@35.67, fee: 2.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2023-12-01 00:00:00:CORE_BUY MTCH ... 544.66@32.07, fee: 17.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL GOOGL ... 133.98@136.96, fee: 18.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL JD ... 705.31@24.8, fee: 17.49

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL ALGN ... 79.46@268.92, fee: 21.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL CMCSA ... 490.88@37.15, fee: 18.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL ENPH ... 164.41@131.24, fee: 21.58

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_SELL MTCH ... 544.66@34.96, fee: 19.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY CEG ... 169.85@113.49, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY ON ... 1.23@81.45, fee: 0.1

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY AAPL ... 105.01@183.56, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY SNPS ... 38.63@498.97, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY VRSN ... 97.08@198.55, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY ABNB ... 143.34@134.48, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-01-02 00:00:00:CORE_BUY ADBE ... 33.23@580.07, fee: 19.3

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_SELL CEG ... 169.85@125.68, fee: 21.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_SELL SNPS ... 38.63@540.0, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_SELL ABNB ... 143.34@146.49, fee: 21.0

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_SELL ADBE ... 33.23@627.91, fee: 20.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY ON ... 46.21@70.19, fee: 3.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY AAPL ... 2.76@184.77, fee: 0.51

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY JD ... 980.0@20.26, fee: 19.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY LULU ... 42.98@461.94, fee: 19.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY VRSN ... 3.86@197.26, fee: 0.76

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY ENPH ... 188.3@105.44, fee: 19.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-02-01 00:00:00:CORE_BUY XEL ... 353.44@56.18, fee: 19.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_SELL ON ... 283.58@81.14, fee: 23.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_SELL JD ... 9.64@20.97, fee: 0.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_SELL ENPH ... 188.3@129.66, fee: 24.42

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY INSM ... 723.05@28.06, fee: 20.31

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY AAPL ... 6.61@177.88, fee: 1.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY LULU ... 1.4@458.5, fee: 0.64

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY VRSN ... 4.86@192.31, fee: 0.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY ADBE ... 35.54@570.93, fee: 20.31

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-03-01 00:00:00:CORE_BUY XEL ... 93.09@45.54, fee: 4.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_SELL INSM ... 723.05@26.72, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_SELL JD ... 970.36@25.31, fee: 24.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_SELL XEL ... 446.53@49.48, fee: 22.09

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY ZS ... 103.75@192.13, fee: 19.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY AAPL ... 4.37@168.34, fee: 0.74

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY MDLZ ... 306.07@65.13, fee: 19.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY LULU ... 7.5@385.2, fee: 2.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY VRSN ... 1.39@186.51, fee: 0.26

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY ADBE ... 4.27@502.09, fee: 2.15

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-04-01 00:00:00:CORE_BUY PANW ... 142.67@139.71, fee: 19.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL ZS ... 103.75@172.31, fee: 17.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL AAPL ... 118.75@167.62, fee: 19.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL MDLZ ... 306.07@65.99, fee: 20.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL LULU ... 51.88@354.4, fee: 18.39

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL ADBE ... 39.81@469.39, fee: 18.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_SELL PANW ... 142.67@143.67, fee: 20.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY ADSK ... 90.36@210.71, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY ALGN ... 66.92@284.52, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY CDNS ... 69.35@274.55, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY CMCSA ... 581.58@32.74, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY MSFT ... 49.05@388.13, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY VRSN ... 6.11@168.52, fee: 1.03

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-05-01 00:00:00:CORE_BUY MTCH ... 635.99@29.94, fee: 19.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_SELL CDNS ... 69.35@286.15, fee: 19.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_SELL CMCSA ... 581.58@33.92, fee: 19.73

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_SELL MSFT ... 49.05@407.12, fee: 19.97

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_SELL VRSN ... 113.3@172.32, fee: 19.52

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_SELL MTCH ... 635.99@29.78, fee: 18.94

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY ZS ... 113.09@169.02, fee: 19.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY ADSK ... 0.58@210.82, fee: 0.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY ALGN ... 8.38@254.53, fee: 2.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY LULU ... 62.34@306.62, fee: 19.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY ABNB ... 130.7@146.25, fee: 19.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY ADBE ... 43.54@439.02, fee: 19.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-06-03 00:00:00:CORE_BUY WDAY ... 90.66@210.83, fee: 19.13

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL ZS ... 113.09@198.62, fee: 22.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL ADSK ... 90.94@245.83, fee: 22.36

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL ALGN ... 75.3@238.64, fee: 17.97

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL ABNB ... 130.7@151.63, fee: 19.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL ADBE ... 43.54@560.01, fee: 24.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_SELL WDAY ... 90.66@224.72, fee: 20.37

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY DLTR ... 194.3@107.25, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY JD ... 861.49@24.19, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY MDLZ ... 339.97@61.3, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY LULU ... 6.77@302.36, fee: 2.05

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY FAST ... 700.52@29.75, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY ENPH ... 214.26@97.26, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-07-01 00:00:00:CORE_BUY PYPL ... 363.59@57.31, fee: 20.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_SELL JD ... 861.49@23.67, fee: 20.39

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_SELL MDLZ ... 339.97@64.18, fee: 21.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_SELL FAST ... 700.52@32.48, fee: 22.75

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_SELL ENPH ... 214.26@109.68, fee: 23.5

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_SELL PYPL ... 363.59@64.75, fee: 23.54

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY CEG ... 120.72@175.47, fee: 21.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY AMD ... 159.83@132.54, fee: 21.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY DLTR ... 18.65@99.75, fee: 1.86

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY ALGN ... 92.77@228.33, fee: 21.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY CDNS ... 81.22@260.81, fee: 21.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY LULU ... 16.16@249.05, fee: 4.03

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-08-01 00:00:00:CORE_BUY ABNB ... 156.81@135.09, fee: 21.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_SELL CEG ... 120.72@176.0, fee: 21.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_SELL AMD ... 159.83@136.94, fee: 21.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_SELL ALGN ... 92.77@226.5, fee: 21.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_SELL CDNS ... 1.79@256.28, fee: 0.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_SELL LULU ... 6.39@258.08, fee: 1.65

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_BUY DLTR ... 36.26@81.65, fee: 2.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_BUY GOOGL ... 129.97@156.16, fee: 20.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_BUY MSFT ... 50.26@403.83, fee: 20.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_BUY SNPS ... 42.18@481.22, fee: 20.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-09-03 00:00:00:CORE_BUY ABNB ... 20.18@114.98, fee: 2.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL GOOGL ... 129.97@165.93, fee: 21.57

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL CDNS ... 0.72@263.32, fee: 0.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL LULU ... 78.87@266.45, fee: 21.02

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL MSFT ... 50.26@414.93, fee: 20.85

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL SNPS ... 0.35@495.56, fee: 0.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_SELL ABNB ... 11.81@125.47, fee: 1.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_BUY ZS ... 123.74@166.99, fee: 20.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_BUY DLTR ... 44.89@70.44, fee: 3.17

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_BUY INSM ... 283.54@72.88, fee: 20.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-10-01 00:00:00:CORE_BUY ADBE ... 41.1@502.8, fee: 20.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_SELL ZS ... 123.74@182.59, fee: 22.59

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_SELL DLTR ... 294.1@66.6, fee: 19.59

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_SELL CDNS ... 78.71@282.09, fee: 22.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_SELL SNPS ... 41.82@518.4, fee: 21.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_SELL ABNB ... 165.17@136.46, fee: 22.54

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY INSM ... 25.61@68.32, fee: 1.75

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY ALGN ... 100.98@208.58, fee: 21.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY MDLZ ... 325.15@64.78, fee: 21.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY MSFT ... 52.04@404.75, fee: 21.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY VRSN ... 121.02@174.04, fee: 21.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY ENPH ... 252.13@83.54, fee: 21.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-11-01 00:00:00:CORE_BUY ADBE ... 2.65@482.8, fee: 1.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_SELL INSM ... 309.15@72.42, fee: 22.39

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_SELL ALGN ... 100.98@234.14, fee: 23.64

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_SELL MSFT ... 52.04@425.93, fee: 22.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_SELL VRSN ... 121.02@189.61, fee: 22.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_SELL ADBE ... 43.75@516.2, fee: 22.58

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY ADI ... 100.17@217.3, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY AMD ... 153.23@142.06, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY JD ... 619.38@35.14, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY MDLZ ... 28.75@61.68, fee: 1.78

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY ENPH ... 38.4@75.12, fee: 2.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY MTCH ... 682.87@31.88, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2024-12-02 00:00:00:CORE_BUY WDAY ... 86.57@251.46, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL ADI ... 100.17@206.71, fee: 20.71

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL JD ... 619.38@32.11, fee: 19.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL MDLZ ... 353.9@56.71, fee: 20.07

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL ENPH ... 290.53@71.36, fee: 20.73

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL MTCH ... 682.87@31.31, fee: 21.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_SELL WDAY ... 86.57@251.84, fee: 21.8

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY AMD ... 16.28@120.63, fee: 1.97

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY ON ... 330.45@61.71, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY ZS ... 112.25@181.66, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY CMCSA ... 626.01@32.57, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY SNPS ... 42.24@482.75, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY FAST ... 592.09@34.44, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-01-02 00:00:00:CORE_BUY ADBE ... 46.24@441.0, fee: 20.41

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_SELL ZS ... 112.25@200.0, fee: 22.45

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_SELL SNPS ... 42.24@520.25, fee: 21.98

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_SELL FAST ... 33.95@35.91, fee: 1.22

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_SELL ADBE ... 46.24@438.6, fee: 20.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY AMD ... 5.89@114.27, fee: 0.67

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY ON ... 68.16@50.26, fee: 3.43

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY MDLZ ... 365.25@54.72, fee: 20.0

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY CMCSA ... 61.79@29.13, fee: 1.8

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY MSFT ... 49.21@406.1, fee: 20.0

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-02-03 00:00:00:CORE_BUY ENPH ... 312.7@63.91, fee: 20.0

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_SELL ON ... 398.61@44.91, fee: 17.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_SELL MDLZ ... 365.25@62.69, fee: 22.9

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_SELL CMCSA ... 687.8@31.58, fee: 21.72

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_SELL MSFT ... 49.21@384.71, fee: 18.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_SELL FAST ... 558.14@36.23, fee: 20.22

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY AMD ... 21.61@98.23, fee: 2.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY ADSK ... 70.95@272.03, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY GOOGL ... 116.16@166.14, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY ALGN ... 110.23@175.09, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY CDNS ... 79.84@241.74, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY ENPH ... 53.28@52.87, fee: 2.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-03-03 00:00:00:CORE_BUY PYPL ... 279.1@69.15, fee: 19.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL AMD ... 197.0@102.78, fee: 20.25

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL ADSK ... 70.95@264.61, fee: 18.77

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL ALGN ... 110.23@158.08, fee: 17.42

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL CDNS ... 79.84@258.79, fee: 20.66

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL ENPH ... 365.98@62.39, fee: 22.83

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_SELL PYPL ... 279.1@65.53, fee: 18.29

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY ON ... 483.64@40.2, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY GOOGL ... 8.47@156.43, fee: 1.33

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY LULU ... 69.53@279.63, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY MSFT ... 51.37@378.47, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY ADBE ... 50.74@383.2, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY PANW ... 113.49@171.31, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-04-01 00:00:00:CORE_BUY WDAY ... 82.9@234.53, fee: 19.46

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_SELL ON ... 483.64@39.6, fee: 19.15

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_SELL GOOGL ... 124.63@160.65, fee: 20.02

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_SELL MSFT ... 51.37@421.26, fee: 21.64

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_SELL PANW ... 113.49@186.27, fee: 21.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_SELL WDAY ... 82.9@246.61, fee: 20.44

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY INSM ... 274.89@72.64, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY JD ... 629.54@31.72, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY LULU ... 5.02@268.6, fee: 1.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY CMCSA ... 666.56@29.96, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY ENPH ... 448.22@44.55, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY MTCH ... 675.82@29.55, fee: 19.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-05-01 00:00:00:CORE_BUY ADBE ... 2.72@374.63, fee: 1.02

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_SELL LULU ... 74.55@322.95, fee: 24.08

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_SELL ADBE ... 53.45@403.4, fee: 21.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY INSM ... 12.3@71.68, fee: 0.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY AAPL ... 102.17@200.9, fee: 20.55

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY JD ... 19.3@31.73, fee: 0.61

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY CMCSA ... 10.46@30.41, fee: 0.32

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY ENPH ... 49.9@41.32, fee: 2.06

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY MTCH ... 22.99@29.46, fee: 0.68

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-06-02 00:00:00:CORE_BUY WDAY ... 82.85@247.75, fee: 20.55

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_SELL AAPL ... 102.17@207.0, fee: 21.15

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_SELL INSM ... 287.19@97.62, fee: 28.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_SELL CMCSA ... 677.03@32.18, fee: 21.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_SELL MTCH ... 698.81@31.59, fee: 22.07

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY COST ... 22.34@980.44, fee: 21.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY JD ... 46.79@31.57, fee: 1.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY LULU ... 89.35@245.12, fee: 21.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY ENPH ... 38.75@40.91, fee: 1.59

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY ADBE ... 55.86@392.1, fee: 21.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY XEL ... 328.59@66.65, fee: 21.92

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-07-01 00:00:00:CORE_BUY WDAY ... 8.95@239.23, fee: 2.14

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_SELL COST ... 22.34@948.5, fee: 21.19

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_SELL JD ... 695.62@29.85, fee: 20.76

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_SELL LULU ... 89.35@193.33, fee: 17.27

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_SELL XEL ... 328.59@71.27, fee: 23.42

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_SELL WDAY ... 91.8@222.22, fee: 20.4

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY ALGN ... 145.48@136.52, fee: 19.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY CMCSA ... 683.19@29.07, fee: 19.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY VRSN ... 75.77@262.12, fee: 19.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY ENPH ... 96.63@31.43, fee: 3.04

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY PYPL ... 298.5@66.53, fee: 19.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY ADBE ... 1.41@347.8, fee: 0.49

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-08-01 00:00:00:CORE_BUY PANW ... 114.88@172.88, fee: 19.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL CMCSA ... 683.19@30.51, fee: 20.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL VRSN ... 75.77@270.63, fee: 20.51

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL ENPH ... 633.5@36.98, fee: 23.43

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL PYPL ... 298.5@68.66, fee: 20.49

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL ADBE ... 57.27@345.63, fee: 19.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_SELL PANW ... 114.88@190.52, fee: 21.89

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY ON ... 427.83@48.94, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY ZS ... 76.26@274.57, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY COST ... 22.4@934.86, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY JD ... 686.65@30.49, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY ALGN ... 7.61@137.16, fee: 1.05

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY MDLZ ... 350.63@59.72, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-09-02 00:00:00:CORE_BUY LULU ... 104.58@200.21, fee: 20.96

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_SELL ON ... 427.83@48.35, fee: 20.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_SELL ZS ... 76.26@304.53, fee: 23.22

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_SELL JD ... 686.65@34.92, fee: 23.98

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_SELL MDLZ ... 350.63@61.54, fee: 21.58

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_SELL LULU ... 104.58@177.57, fee: 18.57

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY DLTR ... 233.62@90.32, fee: 21.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY COST ... 0.77@913.47, fee: 0.7

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY ALGN ... 12.84@127.52, fee: 1.64

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY CMCSA ... 754.9@27.95, fee: 21.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY SNPS ... 43.17@488.78, fee: 21.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY ABNB ... 172.5@122.32, fee: 21.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-10-01 00:00:00:CORE_BUY PYPL ... 319.28@66.09, fee: 21.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL DLTR ... 233.62@100.85, fee: 23.56

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL COST ... 0.13@925.43, fee: 0.12

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL ALGN ... 165.92@138.53, fee: 22.99

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL SNPS ... 43.17@445.72, fee: 19.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL ABNB ... 172.5@126.8, fee: 21.87

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_SELL PYPL ... 319.28@67.75, fee: 21.63

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY MDLZ ... 385.15@55.19, fee: 21.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY CMCSA ... 119.45@24.37, fee: 2.91

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY VRSN ... 87.74@242.26, fee: 21.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY FAST ... 523.57@40.6, fee: 21.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY ENPH ... 720.3@29.51, fee: 21.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-11-03 00:00:00:CORE_BUY MTCH ... 665.53@31.94, fee: 21.28

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL COST ... 23.04@909.4, fee: 20.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL MDLZ ... 385.15@54.95, fee: 21.16

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL VRSN ... 87.74@249.43, fee: 21.88

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL FAST ... 523.57@39.72, fee: 20.79

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL ENPH ... 720.3@28.58, fee: 20.59

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_SELL MTCH ... 665.53@33.17, fee: 22.07

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY ZS ... 86.97@243.28, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY JD ... 733.12@28.86, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY CMCSA ... 9.43@24.01, fee: 0.23

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY ABNB ... 178.1@118.8, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY ADBE ... 65.54@322.85, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY PANW ... 112.71@187.73, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2025-12-01 00:00:00:CORE_BUY WDAY ... 99.17@213.35, fee: 21.18

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_SELL CMCSA ... 883.79@26.69, fee: 23.58

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_SELL ABNB ... 178.1@133.01, fee: 23.69

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_SELL ADBE ... 65.54@333.3, fee: 21.84

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY ZS ... 10.12@220.57, fee: 2.23

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY COST ... 25.07@852.1, fee: 21.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY JD ... 18.14@28.51, fee: 0.52

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY PYPL ... 369.69@57.77, fee: 21.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY XEL ... 290.29@73.58, fee: 21.38

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY PANW ... 6.7@179.37, fee: 1.2

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-01-02 00:00:00:CORE_BUY WDAY ... 4.91@205.79, fee: 1.01

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_SELL ZS ... 97.09@200.61, fee: 19.48

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_SELL COST ... 25.07@966.96, fee: 24.24

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_SELL JD ... 751.26@27.55, fee: 20.7

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_SELL XEL ... 290.29@73.4, fee: 21.31

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_SELL PANW ... 119.41@175.42, fee: 20.95

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY CEG ... 75.94@270.1, fee: 20.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY ADSK ... 80.25@255.57, fee: 20.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY CDNS ... 70.92@289.19, fee: 20.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY MSFT ... 48.66@421.49, fee: 20.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY PYPL ... 25.85@52.0, fee: 1.35

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY ADBE ... 69.91@293.38, fee: 20.53

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-02-02 00:00:00:CORE_BUY WDAY ... 14.53@173.38, fee: 2.52

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_SELL CEG ... 75.94@326.22, fee: 24.77

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_SELL ADSK ... 80.25@246.94, fee: 19.82

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_SELL CDNS ... 70.92@303.36, fee: 21.52

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_SELL PYPL ... 395.54@45.34, fee: 17.93

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY ZS ... 131.93@148.58, fee: 19.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY JD ... 770.46@25.44, fee: 19.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY MSFT ... 0.78@397.69, fee: 0.31

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY SNPS ... 46.16@424.66, fee: 19.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY ADBE ... 5.44@260.88, fee: 1.42

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY PANW ... 130.55@150.15, fee: 19.62

[2026-07-24 00:04:01] INFO [backtest_logger]:     2026-03-02 00:00:00:CORE_BUY WDAY ... 28.02@134.01, fee: 3.76

                 Core_NAV  Tactical_NAV      Total_NAV
Date
2026-03-25  134362.245994           0.0  134362.245994
2026-03-26  134397.714880           0.0  134397.714880
2026-03-27  129264.663758           0.0  129264.663758
2026-03-30  132319.396169           0.0  132319.396169
2026-03-31  135451.600713           0.0  135451.600713

In [16]:
from src import metrics
metrics.calculate_metrics(df_nav[['Total_NAV']])

               CAGR  Sharpe_Ratio  Sortino_Ratio  Max_Drawdown  Calmar_Ratio
Total_NAV  0.074223      0.480603       0.834212      0.248109      0.299155